refatora função de importação
DesignLiquido/delegua pull request #128
Opened 2022-09-12 00:48 UTC by AlessandroFMello

refatora função de carregar bibliotecas para receber atalhos de bibliotecas Delégua

2022-09-12 00:53 UTC, leonelsanchesdasilva requested changes

2022-09-12 00:53 UTC, leonelsanchesdasilva commented on package.json
> +    "@designliquido/delegua-estatistica": "^0.0.5",
Essas dependências acho que não precisa.

2022-09-12 00:53 UTC, leonelsanchesdasilva commented on testes/interpretador.test.ts
> +                    it('estatística' , () => {
Eu usaria aqui um mock na função de importação pra devolver sempre uma resposta positiva, aí não precisa ter a dependência instalada.

2022-09-15 16:03 UTC, AlessandroFMello reviewed
Resolvido com o mock das bibliotecas

2022-09-15 17:54 UTC, leonelsanchesdasilva approved these changes

2022-09-15 17:55 UTC, merged