Fibonacci.birl
DesignLiquido/delegua pull request #474
Opened 2023-08-15 00:16 UTC by ItaloCobains

Nessa branch foi resolvido fibonacci com birl e a integração com a extensão do vscode.

Tendo suporte para:

- [x] Syntax Highlight
- [x] Debug

2023-08-16 12:26 UTC, samuelrvg requested changes

2023-08-16 12:26 UTC, samuelrvg commented on testes/birl/interpretador.test.ts
> +            it.only('Sucesso - Fibonacci', async () => {
@ItaloCobains Remover `only`

2023-08-16 12:26 UTC, samuelrvg commented on fontes/interpretador/dialetos/birl/comum.ts
> +        throw new Error('O primeiro argumento de Escreva precisa ser uma string.');
@ItaloCobains O que acontece se o primeiro argumento for um número? Visto que número também é um literal?

`(typeof argumentos[0].valor !== 'string')` -> Não deveria verificar o valor dessa forma?

2023-08-16 14:25 UTC, ItaloCobains commented on testes/birl/interpretador.test.ts
> +            it.only('Sucesso - Fibonacci', async () => {
Irei remover.

2023-08-16 14:27 UTC, ItaloCobains commented on fontes/interpretador/dialetos/birl/comum.ts
> +        throw new Error('O primeiro argumento de Escreva precisa ser uma string.');
Vou verificar.

2023-08-18 22:56 UTC, ItaloCobains commented on fontes/interpretador/dialetos/birl/comum.ts
> +        throw new Error('O primeiro argumento de Escreva precisa ser uma string.');
Se for passado número ele não da erro e não roda. Mas eu vou adicionar essa verificação faz muito sentido pra mim. Obrigado.

2023-08-19 03:15 UTC, samuelrvg approved these changes

2023-08-19 03:15 UTC, merged