WIP: #524 inicializando e escrevendo vetores
DesignLiquido/delegua pull request #525
Opened 2023-10-02 02:04 UTC by pablotdv

2023-10-02 02:09 UTC, pablotdv commented
Atividade #524

2023-10-02 02:13 UTC, leonelsanchesdasilva requested changes
Está ótimo. Só peguei duas coisas.

2023-10-02 02:13 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +                        this.consumir(tiposDeSimbolos.VIRGULA, 'Esperado vírgula antes da próxima expressão.');
`consumir` já verifica o tipo. Não precisa o `if`.

2023-10-02 02:13 UTC, leonelsanchesdasilva commented on fontes/interpretador/interpretador-base.ts
> +            } else {
Precisa mesmo desse `else`?

2023-10-02 02:16 UTC, pablotdv commented on fontes/interpretador/interpretador-base.ts
> +            } else {
Esse else faz com que a função escreva consiga escrever o vetor no formato [2,3]

2023-10-02 15:21 UTC, samuelrvg requested changes

2023-10-02 15:21 UTC, samuelrvg commented on fontes/interpretador/interpretador-base.ts
> +            } else {
@leonelsanchesdasilva @pablotdv Faria mais sentido validar isso dentro da função `paraTexto` por que, o ternário da linha 954 já obtém o valor que é testado dentro desse método, outra forma seria adicionar essa regra somente no interpretador de Potigol, mas isso teria que testar pra ter mais certeza.

2023-10-03 00:11 UTC, pablotdv commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +                        this.consumir(tiposDeSimbolos.VIRGULA, 'Esperado vírgula antes da próxima expressão.');
Quebrou a atribuição do vetor com a remoção do if

2023-10-03 00:12 UTC, pablotdv commented on fontes/interpretador/interpretador-base.ts
> +            } else {
Removi o if e fiz uma alteração no `paraTexto` para imprimir vetores no formato `[n1, n2]`

2023-10-03 00:14 UTC, leonelsanchesdasilva approved these changes

2023-10-03 00:26 UTC, samuelrvg approved these changes

2023-10-03 00:26 UTC, merged