Decorador para classes
DesignLiquido/delegua pull request #562
Opened 2023-12-22 21:40 UTC by samuelrvg

2023-12-22 21:52 UTC, leonelsanchesdasilva requested changes
Está ótimo. Faltam algumas coisas na avaliação sintática apenas.

2023-12-22 21:52 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +            decoradores.push(new Decorador(this.hashArquivo, tamanhoLinhaAtual, nomeDecorador));
Por que o tamanho da linha é importante?

2023-12-22 21:52 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +            if ([tiposDeSimbolos.CLASSE, tiposDeSimbolos.ARROBA].includes(this.simboloAtual().tipo)) {
E se for função? 

Aquilo que te falei antes: eu acho que seria melhor ter um `resolverDecorador` quando uma arroba é encontrada, empilhando isso numa variável interna, por exemplo, `pilhaDecoradores`. Aí quando uma classe ou função é encontrada, você desempilha a pilha toda pra dentro do construtor da declaração de classe/função.

2023-12-22 22:37 UTC, samuelrvg commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +            decoradores.push(new Decorador(this.hashArquivo, tamanhoLinhaAtual, nomeDecorador));
@leonelsanchesdasilva Com o tamanho da linha, eu pego todos os lexemas, logo tenho o nome do decorador.

2023-12-22 22:40 UTC, samuelrvg commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +            decoradores.push(new Decorador(this.hashArquivo, tamanhoLinhaAtual, nomeDecorador));
@leonelsanchesdasilva Na verdade é só a linha atual mesmo, igual os demais construtos e declaradores.

2023-12-23 00:02 UTC, leonelsanchesdasilva requested changes
Algum ajuste na lógica da pilha vai ser necessário.

2023-12-23 00:02 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        return new FuncaoDeclaracao(simbolo, this.corpoDaFuncao(tipo), null, this.pilhaDecoradores);
Depois disso a pilha deveria esvaziar, não?

2023-12-23 00:02 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        return new Classe(simbolo, superClasse, metodos, null, pilhaDecoradoresClasse);
Idem.

2023-12-28 18:13 UTC, samuelrvg commented on fontes/avaliador-sintatico/avaliador-sintatico.ts
> +        return new FuncaoDeclaracao(simbolo, this.corpoDaFuncao(tipo), null, this.pilhaDecoradores);
@leonelsanchesdasilva Sim, isso já acontece dentro do método `resolverDecorador` linha 941.

2023-12-28 19:51 UTC, leonelsanchesdasilva approved these changes

2023-12-28 19:52 UTC, merged