Formatador codigo potigol
DesignLiquido/delegua pull request #660
Opened 2024-02-20 21:52 UTC by Aristidescosta

resolve #583

2024-02-20 23:45 UTC, ItaloCobains requested changes

2024-02-20 23:45 UTC, ItaloCobains commented on fontes/tipos-de-simbolos/potigol.ts
> +    LÓGICO: 'LÓGICO',
Precisa mesmo do lógico com acento e sem acento ?

2024-02-21 06:43 UTC, Aristidescosta200 commented on fontes/tipos-de-simbolos/potigol.ts
> +    LÓGICO: 'LÓGICO',
Acredito que sim porque os tipos de dados que o avaliador está trazendo está com acentos.

2024-02-21 11:15 UTC, ItaloCobains commented on fontes/tipos-de-simbolos/potigol.ts
> +    LÓGICO: 'LÓGICO',
Assim eu acabei de ver aqui é por causa disso. Me parece algo especifico de potigol.
![image](https://github.com/DesignLiquido/delegua/assets/83548040/cda200a8-bfe0-46bf-b1ba-5846b4a187b1)

2024-02-21 11:16 UTC, ItaloCobains reviewed
Bom trabalho.

2024-02-23 16:24 UTC, leonelsanchesdasilva requested changes
Estamos quase lá. Creio que há mais alguns detalhes a serem acertados.

2024-02-23 16:24 UTC, leonelsanchesdasilva commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +        Real: 'real',
A ideia deste dicionário é, dada uma chave de tipo em Potigol, converter para o tipo correspondente de Delégua, usado internamente. 

O tipo `real` não existe em Delégua (seria `numero` mesmo). Já o tipo `inteiro` existe, então a alteração na linha 63 é pertinente.

2024-02-23 19:38 UTC, Aristidescosta commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +        Real: 'real',
Entendo, vou fazer as alterações agora mesmo.

2024-02-23 19:42 UTC, Aristidescosta commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +        Real: 'real',
@leonelsanchesdasilva 

Mas é possível fazer isso.

```
a = 3.1
escreva(a.qual_tipo)// Real
```

2024-02-24 15:26 UTC, Aristidescosta commented
@leonelsanchesdasilva  Feita as alterações!

2024-02-24 15:31 UTC, ItaloCobains approved these changes

2024-02-24 22:27 UTC, samuelrvg requested changes

2024-02-24 22:27 UTC, samuelrvg commented on testes/potigol/formatador-potigol.test.ts
> +describe('Avaliador sintático', () => {
Aqui não deveria ser `Formatador > Potigol` ?

2024-02-24 22:50 UTC, samuelrvg requested changes

2024-02-24 22:50 UTC, samuelrvg commented on fontes/avaliador-sintatico/dialetos/potigol/avaliador-sintatico-potigol.ts
> +            tipoRetorno = this.simbolos[this.atual];
@Aristidescosta Lembra o motivo do por que remover essa condição -1 ?

2024-02-24 23:24 UTC, leonelsanchesdasilva approved these changes

2024-02-25 02:26 UTC, samuelrvg approved these changes

2024-02-25 02:26 UTC, merged

2024-02-25 02:29 UTC, samuelrvg commented on testes/potigol/formatador-potigol.test.ts
> +describe('Avaliador sintático', () => {
0daa2873d6ac55dd2be01ff8a96ccc4a6c926b2e