Funcao retorna lista
DesignLiquido/delegua pull request #661
Opened 2024-02-21 19:31 UTC by Aristidescosta

resolve https://github.com/DesignLiquido/delegua/issues/653

2024-02-21 19:48 UTC, samuelrvg commented on fontes/interpretador/interpretador-base.ts
> +            console.log(formatoTexto);
remover `console.log`

2024-02-21 20:04 UTC, samuelrvg commented on fontes/interpretador/interpretador-base.ts
> +                retornoVetor = retornoVetor.slice(0, -1);
Já temos algum teste unitário que passa nesse fluxo?

2024-02-21 20:57 UTC, leonelsanchesdasilva requested changes
Favor alterar conforme os comentários do @samuelrvg

2024-02-22 19:15 UTC, samuelrvg approved these changes

2024-02-22 19:30 UTC, samuelrvg commented
@Aristidescosta @leonelsanchesdasilva Por algum motivo os testes estão quebrando local, como sua implementação é bem simples, simulei local na minha branch atualizada com base na `principal`, esse foi o resultado radando `yarn testes-unitarios`.
![Screenshot 2024-02-22 162613](https://github.com/DesignLiquido/delegua/assets/14062631/4df27099-f416-4ace-aa53-751478ee1c6c)

O motivo disso, não sei dizer, mas vale uma investigação depois.

2024-02-22 19:37 UTC, samuelrvg approved these changes

2024-02-22 19:37 UTC, merged